# Generated by Django 4.0.1 on 2022-11-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='images/')),
                ('dname', models.CharField(max_length=55)),
                ('type', models.CharField(max_length=11)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
