# Generated by Django 4.0.1 on 2022-11-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_dish_id_dish__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='_id',
            new_name='id',
        ),
    ]
